

server:
    port: 17010
spring:
    application:
        aliascopy:
            name: iscc-service-test-alias-copy1
        alias:
            name: iscc-service-test-alias
        name: iscc-service-test
