

server:
    port: 17010
spring:
    application:
        aliascopy:
            name: iscc-service-test-alias-copy34
        alias:
            name: iscc-service-test-alias1
        name: iscc-service-test
